### PR TITLE
Split up composer to run phpunit separately

### PR DESCRIPTION
**Pull request by paladox**
Composer test will now be for php linting, phpcs and minus-x

### CODE REVIEW

**Comment by paladox** [comment]
Not sure why this won't work for me on https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/5865

**Comment by paladox** [comment]
@gesinn-it-gea i don't think this works. Some how it's failing because COMPOSER_PARAMS is supplied to composer test (this env will only work with phpunit)

**Comment by paladox** [comment]
I've been trying to think of ways. I'm kinda leaning towards not using "ci" and rather doing like composer-test / composer-phpunit and doing npm-test as well (which will remove the duplicate npm test being run).

**Comment by gesinn-it-gea** [comment]
@paladox I'm not sure I understood the problem completely. I'll try to catch-up.

**Comment by paladox** [comment]
> @paladox I'm not sure I understood the problem completely. I'll try to catch-up.

I'm re-doing SMW composer file to simplify running phpcs (as it's not currently run). I'm removing the duplicate phpcs.xml file. There was two different standards so I'm just going with .phpcs.xml.

**Comment by gesinn-it-gea** [comment]
The original idea in docker-compose-ci was to call "composer-test" or "npm-test". Then it's up to the repo using docker-compose-ci to define the targets in composer.json. Some might for example linting before. Some might have reasons to not lint. Could this be an approach?

Maybe docker-compose-ci is missing an "interface" description for the targets. What do you think @paladox ?

**Comment by gesinn-it-gea** [comment]
@paladox : SMW came in late with to use docker-compose-ci. There might be some left-overs from previous approaches. Did you look into other extensions using docker-compose-ci, like https://github.com/gesinn-it-pub/IDProvider or https://github.com/SemanticMediaWiki/SemanticResultFormats. 

ping @gesinn-it-ilm

**Comment by gesinn-it-gea** [comment]
@paladox are you using docker-compose-ci locally to test / develop already? Because the original idea was to have the same environment locally and on CI. Maybe this helps you finding the right approach. Feel free to ping @gesinn-it-ilm

**Comment by paladox** [comment]
> The original idea in docker-compose-ci was to call "composer-test" or "npm-test". Then it's up to the repo using docker-compose-ci to define the targets in composer.json. Some might for example linting before. Some might have reasons to not lint. Could this be an approach?
> 
> Maybe docker-compose-ci is missing an "interface" description for the targets. What do you think @paladox ?

I'm not sure what you mean by "interface" description for the targets?

Right now my idea is to do something like:

```
	"scripts": {
		"test": [
			"@lint",
			"@phpcs",
			"minus-x check ."
		],
		"test-coverage": [
			"@phpunit-coverage"
		],
		"analyze": [
			"@lint",
			"@phpcs"
		],
		"fix": [
			"@phpcs-fix"
		],
		"lint": "parallel-lint . --exclude vendor --exclude node_modules",
		"phpcs": "phpcs -ps --cache -d memory_limit=2G",
		"phpcs-fix": "phpcbf",
		"phpunit": "php ${MW_INSTALL_PATH:-../..}/tests/phpunit/phpunit.php -c phpunit.xml.dist",
		"phpunit:unit": "@phpunit --testsuite=semantic-mediawiki-unit",
		"phpunit:integration": "@phpunit --testsuite semantic-mediawiki-check,semantic-mediawiki-data-model,semantic-mediawiki-integration,semantic-mediawiki-import,semantic-mediawiki-structure",
		"phpunit-coverage": "@phpunit --testdox --coverage-text --coverage-html coverage/php --coverage-clover coverage/php/coverage.xml",
		"phpdbg": "phpdbg -qrr ${MW_INSTALL_PATH}/tests/phpunit/phpunit.php -c phpunit.xml.dist",
		"minus-x": "minus-x check .",
		"benchmark": "composer phpunit  -- --group semantic-mediawiki-benchmark",
		"quick-benchmark": "php ${MW_INSTALL_PATH}/tests/phpunit/phpunit.php -c ./tests/phpunit/Benchmark/phpunit.quick.xml.dist --group semantic-mediawiki-benchmark"
	}
```

**Comment by paladox** [comment]
Oh I see,

so we could do something like:

```
	"scripts": {
		"test": [
			"@lint",
			"@phpcs",
			"minus-x check ."
		],
		"test-coverage": [
			"@phpunit-coverage"
		],
		"analyze": [
			"@lint",
			"@phpcs"
		],
		"fix": [
			"@phpcs-fix"
		],
		"lint": "parallel-lint . --exclude vendor --exclude node_modules",
		"phpcs": "phpcs -ps --cache -d memory_limit=2G",
		"phpcs-fix": "phpcbf",
		"phpunit": [
                    "@phpunit:unit",
                    "@phpunit:integration"
                ],
		"phpunit-cli": "php ${MW_INSTALL_PATH:-../..}/tests/phpunit/phpunit.php -c phpunit.xml.dist",
		"phpunit:unit": "@phpunit-cli --testsuite=semantic-mediawiki-unit",
		"phpunit:integration": "@phpunit-cli --testsuite semantic-mediawiki-check,semantic-mediawiki-data-model,semantic-mediawiki-integration,semantic-mediawiki-import,semantic-mediawiki-structure",
		"phpunit-coverage": "@phpunit-cli --testdox --coverage-text --coverage-html coverage/php --coverage-clover coverage/php/coverage.xml",
		"phpdbg": "phpdbg -qrr ${MW_INSTALL_PATH}/tests/phpunit/phpunit.php -c phpunit.xml.dist",
		"minus-x": "minus-x check .",
		"benchmark": "composer phpunit  -- --group semantic-mediawiki-benchmark",
		"quick-benchmark": "php ${MW_INSTALL_PATH}/tests/phpunit/phpunit.php -c ./tests/phpunit/Benchmark/phpunit.quick.xml.dist --group semantic-mediawiki-benchmark"
	}
```

**Comment by paladox** [comment]
@gesinn-it-gea ^

**Comment by paladox** [comment]
using "test" for stuff like php linting and code style and then phpunit for as it says on the tin.

what do you think?

**Comment by gesinn-it-gea** [comment]
By interface I mean the targets that are adressed by the Makefile. We have "main entrypoints" like "test", "test-coverage", "analyze", "fix". It's up to you to add things to these entrypoints. If you like linting to be run before test. Just add it to your composer.json

**Comment by gesinn-it-gea** [comment]
In SMW's composer.json might be some left-overs

**Comment by gesinn-it-gea** [comment]
```
"phpunit": [
                    "@phpunit:unit",
                    "@phpunit:integration"
                ],
		"phpunit-cli": "php ${MW_INSTALL_PATH:-../..}/tests/phpunit/phpunit.php -c phpunit.xml.dist",
		"phpunit:unit": "@phpunit-cli --testsuite=semantic-mediawiki-unit",
		"phpunit:integration": "@phpunit-cli --testsuite semantic-mediawiki-check,semantic-mediawiki-data-model,semantic-mediawiki-integration,semantic-mediawiki-import,semantic-mediawiki-structure",
```

yeah, why not

**Comment by paladox** [comment]
Done in https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/5865

**Comment by gesinn-it-gea** [comment]
@paladox btw. many thanks for your contributions!

**Comment by paladox** [comment]
> @paladox btw. many thanks for your contributions!

yw :)

**Comment by paladox** [comment]
I wonder if this broke it @gesinn-it-gea ?

it seems that semantic mediawiki is broken as well

**Comment by paladox** [comment]
Seems that https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/5865 works or fixes it?

**Comment by paladox** [comment]
The only thing I’m thinking about is don’t we need to have a clean db for the unit test then one for the integration tests. 

That doesn’t happen when phpunit is ran and then in it, it runs unit and integration tests.

**Pull request merged**
